import {soapGrades,soapVariantSpecifications} from './brochure';
export type Product={slug:string;name:string;division:'industrial'|'food';image:string;summary:string;applications:string[];variants:string[];details:[string,string][];variantSpecifications?:Record<string,[string,string][]>;brochure?:boolean};
export const products:Product[]=[
{slug:'soap-noodles',name:'Soap noodles',division:'industrial',image:'soap.png',summary:'Soap-making inputs for toilet bars and laundry soaps, supported by our Pakistani production partnership. Compare grades and discuss your formulation with our technical team.',applications:['Toilet soap production','Laundry soap manufacturing','Custom soap formulations'],variants:soapGrades.map(grade=>grade.name),variantSpecifications:soapVariantSpecifications,brochure:true,details:[['Product family','Soap-making inputs'],['Supplier range','NIMIR'],['TFM (total fatty matter)','72% or 78% for specified grades; see individual variants'],['Storage','Ambient'],['Shelf life','6 months for Swing; 12 months for other listed grades'],['Packaging & availability','Confirm the selected grade and current order format'],['Technical support','Formulation discussions and laboratory-tested batch reports']]},
{slug:'glycerine',name:'Glycerine',division:'industrial',image:'glycerine.png',summary:'A versatile input for soap, personal care and industrial formulations. Our brochure lists the T-1 range; discuss the specification your application requires with our team.',applications:['Soap manufacturing','Cosmetics and personal care','Industrial formulations'],variants:['T-1'],brochure:true,variantSpecifications:{'T-1':[['Storage','Ambient'],['Shelf life','12 months']]},details:[['Product family','Glycerine'],['Brochure range','T-1'],['Storage','Ambient'],['Shelf life','12 months'],['Grade & purity','Confirm the required specification; not stated in the brochure'],['Packaging & availability','Available on enquiry'],['Documentation','Request product-specific technical information']]},
{slug:'stearic-acid',name:'Stearic acid',division:'industrial',image:'stearic.jpg',summary:'A formulation input for soap, personal care and industrial production. Find a suitable grade for the structure and performance your product needs.',applications:['Soap bars','Creams and lotions','Candles and industrial applications'],variants:['Industrial grade','Cosmetic grade'],details:[['Product family','Fatty acids'],['Grade selection','Industrial and cosmetic enquiries'],['Specifications','Confirm against supplier documentation'],['Packaging & availability','Available on enquiry']]},
{slug:'solvents',name:'Paint-making solvents',division:'industrial',image:'solvents.jpg',summary:'Source solvents for paint and coatings production. Share the solvent name, specification and volume you need so our team can assess your requirement.',applications:['Decorative paints','Industrial coatings','Manufacturing'],variants:[],details:[['Product family','Paint and coating inputs'],['Solvent selection','Specify the chemical and required grade'],['Safety documentation','Request the relevant safety data sheet'],['Packaging & availability','Available on enquiry']]},
{slug:'granola',name:'Granola',division:'food',image:'granola-detail/packs.jpg',summary:'Explore Nicnax Almond Cranberry, Fruity Delight and Tropical Fruit granola for breakfast bowls, yoghurt toppings and everyday snacking. Discuss retail packs and carton supply for your shelves or food-service menu.',applications:['Retail and supermarkets','Breakfast and food service','Wholesale distribution'],variants:['Almond Cranberry Granola','Fruity Delight Granola','Tropical Fruit Granola'],details:[['Brand','Nicnax'],['Range','Almond Cranberry, Fruity Delight and Tropical Fruit'],['Serving ideas','With milk, over yoghurt or fruit, or enjoyed as a snack'],['Pack & carton sizes','Confirm with our team for your selected flavour'],['Ingredients & allergens','Refer to the current product label for each flavour'],['Shelf life & storage','Confirm for the selected variant']]},
{slug:'nutee',name:'Nutee peanut butter',division:'food',image:'granola-detail/nutee.jpg',summary:'Smooth peanut butter for toast, breakfast bowls and everyday snacks. Nutee brings a peanut spread to your retail shelves or café menu, with jar packaging shown alongside the Nicnax granola range. Talk to our team about current packs and supply quantities.',applications:['Retail and supermarket spread aisles','Cafés, toast and breakfast menus','Wholesale and food-service supply'],variants:[],details:[['Brand','Nutee'],['Product type','Smooth peanut butter'],['Texture','Smooth, as identified on the supplied jars'],['Serving ideas','Spread on toast, stir into porridge or pair with granola and fruit'],['Packaging','Jars; confirm current jar weight and carton quantity'],['Ingredients & allergens','Contains peanuts. Check the current label for the full ingredient list and any additional allergen declarations'],['Shelf life & storage','Follow the current jar label, including storage guidance after opening'],['Ordering','Share your quantity and delivery location; confirm current availability with our team']]},
{slug:'oatmeal',name:'Oatmeal',division:'food',image:'oatmeal.webp',summary:'Breakfast essentials for everyday routines. Explore finished oatmeal products for retail and food-service supply.',applications:['Retail shelves','Breakfast menus','Food-service supply'],variants:[],details:[['Product family','Finished breakfast products'],['Available range','Ask about current brands and variants'],['Pack & carton sizes','Available on enquiry'],['Storage & ingredients','Refer to the selected product label']]},
{slug:'margarine',name:'Margarine',division:'food',image:'margarine.jpg',summary:'For kitchens, bakeries and everyday tables. Discuss the margarine formats best suited to your retail or food-service requirements.',applications:['Household retail','Baking','Food service'],variants:[],details:[['Product family','Spreads and baking products'],['Range & formats','Confirm the product for your application'],['Pack & carton sizes','Available on enquiry'],['Storage & ingredients','Refer to the selected product label']]}
];
export const divisionName=(division:string)=>division==='industrial'?'Industrial raw materials':'Food & consumer products';

