import Link from 'next/link';
import HeroBanner from '@/components/hero-banner';
import PartnerLogos from '@/components/partner-logos';
import { ArrowUpRight, ArrowRight, Factory, Package, Layers3, Check } from 'lucide-react';
export default function Home(){return <main id="main">
<HeroBanner/>
<section className="divisions wrap" id="industries"><article><Factory className="line-icon"/><span className="index">01</span><h2>Industrial materials</h2><p>Essential inputs for the people making what comes next.</p><div className="chips"><Link href="/products/soap-noodles">Soap noodles</Link><Link href="/products/glycerine">Glycerine</Link><Link href="/products/stearic-acid">Stearic acid</Link><Link href="/products/solvents">Solvents</Link></div><Link className="text-link" href="/products?division=industrial">Explore raw materials <ArrowRight size={19}/></Link></article><article><Package className="line-icon"/><span className="index">02</span><h2>Food & consumer products</h2><p>Thoughtfully sourced products for shelves, kitchens and everyday life.</p><div className="chips"><Link href="/products/granola">Granola</Link><Link href="/products/oatmeal">Oatmeal</Link><Link href="/products/margarine">Margarine</Link></div><Link className="text-link" href="/products?division=food">Explore food products <ArrowRight size={19}/></Link></article><article><Layers3 className="line-icon"/><span className="index">03</span><h2>Built around your business</h2><p>Product knowledge and local support, from requirement to supply.</p><div className="chips"><span>Manufacturing</span><span>Personal care</span><span>Paints & coatings</span><span>Retail & food service</span></div><Link className="text-link" href="/contact">Discuss your requirements <ArrowRight size={19}/></Link></article></section>
<section className="partner-strip"><div className="wrap"><div className="section-top"><p className="eyebrow">CONNECTED THROUGH STRONG PARTNERSHIPS</p><Link className="text-link" href="/partners">Our partners <ArrowRight size={18}/></Link></div><PartnerLogos/></div></section>
<section className="wrap range-section"><div className="section-top"><div><p className="eyebrow">OUR PRODUCT RANGE</p><h2 className="display-heading">Good business starts<br/>with the right products.</h2></div><Link className="text-link" href="/products">View all products <ArrowUpRight size={18}/></Link></div><div className="featured-grid">{[{slug:'soap-noodles',name:'Soap noodles',type:'INDUSTRIAL RAW MATERIALS',image:'soap.png'},{slug:'granola',name:'Granola',type:'FOOD & CONSUMER PRODUCTS',image:'granola.jpg'},{slug:'glycerine',name:'Glycerine',type:'INDUSTRIAL RAW MATERIALS',image:'glycerine.png'}].map(p=><Link className="product-card" href={`/products/${p.slug}`} key={p.slug}><div className="product-image"><img src={`/images/${p.image}`} alt={p.name} loading="lazy"/><span className="circle-arrow"><ArrowUpRight size={22}/></span></div><p className="eyebrow">{p.type}</p><h3>{p.name}</h3></Link>)}</div></section>
<section className="approach"><div className="wrap approach-grid"><div><p className="eyebrow">THE IMOKO APPROACH</p><h2 className="display-heading">Global connections.<br/><em>Local understanding.</em></h2><p>We combine direct production relationships in Pakistan with Nigerian market knowledge. From custom soap formulations to flexible supply volumes, our team helps you plan the inputs your business needs.</p><Link className="text-link" href="/about">Get to know IMOKO <ArrowUpRight size={18}/></Link></div><div className="steps">{[['Understand your needs','Tell us what you make, the product you need and where you need it.'],['Find the right fit','Discuss grades, moisture content and total fatty matter, with technical support and batch reports.'],['Coordinate your supply','Plan quantities around your factory’s tonnage requirements, with current availability confirmed by our team.']].map(([title,copy],i)=><div className="step" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div><Check size={18}/></div>)}</div></div></section>
<section className="wrap enquiry-banner"><p className="eyebrow">LET’S MOVE YOUR BUSINESS FORWARD</p><div><h2 className="display-heading">What can we help<br/>you source?</h2><Link className="button" href="/contact">Start a conversation <ArrowUpRight size={20}/></Link></div></section></main>}

