import Link from 'next/link';
import HeroBanner from '@/components/hero-banner';
import PartnerLogos from '@/components/partner-logos';
import HomeDivisions from '@/components/home-divisions';
import { ArrowUpRight, ArrowRight, Check } from 'lucide-react';
export default function Home(){return <main id="main">
<HeroBanner/>
<HomeDivisions/>
<section className="partner-strip"><div className="wrap"><div className="section-top"><p className="eyebrow">CONNECTED THROUGH STRONG PARTNERSHIPS</p><Link className="text-link" href="/partners">Our partners <ArrowRight size={18}/></Link></div><PartnerLogos/></div></section>
<section className="wrap range-section"><div className="section-top"><div><p className="eyebrow">OUR PRODUCT RANGE</p><h2 className="display-heading">Good business starts with the right products.</h2></div><Link className="text-link" href="/products">View all products <ArrowUpRight size={18}/></Link></div><div className="featured-grid">{[{slug:'soap-noodles',name:'Soap noodles',type:'INDUSTRIAL RAW MATERIALS',image:'soap-bags/palm-bright-white-standing.jpg'},{slug:'granola',name:'Granola',type:'FOOD & CONSUMER PRODUCTS',image:'home-granola-products.jpg'},{slug:'glycerine',name:'Glycerine',type:'INDUSTRIAL RAW MATERIALS',image:'glycerine.png'}].map(p=><Link className="product-card" href={`/products/${p.slug}`} key={p.slug}><div className={p.slug==='soap-noodles'?'product-image product-image-soap-photo':p.slug==='granola'?'product-image product-image-granola-photo':'product-image'}><img src={`/images/${p.image}`} alt={p.name} loading="lazy"/><span className="circle-arrow"><ArrowUpRight size={22}/></span></div><p className="eyebrow">{p.type}</p><h3>{p.name}</h3></Link>)}</div></section>
<section className="approach"><div className="wrap approach-grid"><div><p className="eyebrow">THE IMOKO APPROACH</p><h2 className="display-heading">Global connections.<br/><em>Local understanding.</em></h2><p>We combine direct production relationships in Pakistan with Nigerian market knowledge. From custom soap formulations to flexible supply volumes, our team helps you plan the inputs your business needs.</p><Link className="text-link" href="/about">Get to know IMOKO <ArrowUpRight size={18}/></Link></div><div className="steps">{[['Understand your needs','Tell us what you make, the product you need and where you need it.'],['Find the right fit','Discuss grades, moisture content and total fatty matter, with technical support and batch reports.'],['Coordinate your supply','Plan quantities around your factory’s tonnage requirements, with current availability confirmed by our team.']].map(([title,copy],i)=><div className="step" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div><Check size={18}/></div>)}</div></div></section>
<section className="wrap enquiry-banner"><p className="eyebrow">LET’S MOVE YOUR BUSINESS FORWARD</p><div><h2 className="display-heading">What can we help<br/>you source?</h2><Link className="button" href="/contact">Start a conversation <ArrowUpRight size={20}/></Link></div></section></main>}

