'use client';
import {useState,useEffect} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,Download,Check} from 'lucide-react';
type Fields={name:string;company:string;email:string;product:string;variant:string;quantity:string;location:string;notes:string};
function makeDraft(f:Fields){return `IMOKO PRODUCT ENQUIRY\n\nName: ${f.name}\nCompany: ${f.company}\nEmail: ${f.email}\nProduct: ${f.product}\nGrade / variant: ${f.variant||'Please advise'}\nQuantity: ${f.quantity}\nDelivery location: ${f.location}\n\nNotes:\n${f.notes||'None'}\n`;}
export default function QuoteForm({initialProduct,initialVariant}:{initialProduct:string;initialVariant:string}){const [fields,setFields]=useState<Fields>({name:'',company:'',email:'',product:initialProduct,variant:initialVariant,quantity:'',location:'',notes:''});const [draft,setDraft]=useState('');const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'stage_enquiry_product',description:'Fill the visible local enquiry product and optional variant. Does not send or save an enquiry.',inputSchema:{type:'object',properties:{product:{type:'string',minLength:1,maxLength:120},variant:{type:'string',maxLength:120}},required:['product'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const value=input as {product?:unknown;variant?:unknown};if(!value||typeof value.product!=='string'||!value.product.trim()||value.product.length>120||(value.variant!==undefined&&(typeof value.variant!=='string'||value.variant.length>120)))throw new Error('Provide a product name and optional variant, each under 121 characters.');flushSync(()=>{setFields(f=>({...f,product:value.product as string,variant:(value.variant as string)||''}));setDraft('')});return {staged:true,sent:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
const edit=(key:keyof Fields,value:string)=>{setFields(f=>({...f,[key]:value}));setDraft('');setCopied(false);setCopyError(false)};
return <section className="quote-panel"><p className="eyebrow">YOUR REQUIREMENT</p><h2>Make an enquiry</h2><p className="preview-note">Prepare and download an enquiry draft. Nothing is sent from this form.</p><form onSubmit={e=>{e.preventDefault();setDraft(makeDraft(fields));setCopied(false);setCopyError(false)}}><div className="form-grid">{([['name','Full name','text',true],['company','Company','text',true],['email','Email address','email',true],['product','Product','text',true],['variant','Grade / variant (optional)','text',false],['quantity','Quantity & unit','text',true],['location','Delivery city / state','text',true]] as const).map(([key,label,type,required])=><div className={key==='location'?'full-field':''} key={key}><label htmlFor={key}>{label}{required&&<span aria-hidden="true"> *</span>}</label><input id={key} name={key} type={type} required={required} maxLength={key==='email'?254:120} value={fields[key]} onChange={e=>edit(key,e.target.value)} autoComplete={key==='name'?'name':key==='email'?'email':key==='company'?'organization':undefined} placeholder={key==='quantity'?'e.g. 50 bags or 20 cartons':undefined}/></div>)}<div className="full-field"><label htmlFor="notes">Additional details (optional)</label><textarea id="notes" name="notes" rows={4} maxLength={3000} value={fields.notes} onChange={e=>edit('notes',e.target.value)} placeholder="Specifications, delivery requirements or questions…"/></div></div><p className="small-note">* Required fields</p><button className="button" type="submit">Prepare enquiry <ArrowUpRight size={18}/></button></form>{draft&&<div className="draft-result"><p role="status"><Check size={18}/> Your enquiry draft is ready. It has not been sent.</p><pre>{draft}</pre><div className="actions"><button className="button" type="button" onClick={()=>{const blob=new Blob([draft],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='imoko-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download draft <Download size={16}/></button><button className="text-link" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopied(true);setCopyError(false)}catch{setCopyError(true)}}}>{copied?'Copied':'Copy draft'}</button></div>{copyError&&<p role="alert">Copying is unavailable. Download the draft instead.</p>}</div>}</section>}
